<?php require('template/header.phtml') ?>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<section id="plans">
    <div class="container">
        <div class="row">
    <br>
    <table class="table table-hover">



        <?php foreach ($view->campsiteDataSet as $campsiteData)
        { $campsiteDataSet=$campsiteData;
            echo

                '
                        <!-- item -->
                        <div class="col-md-4 text-center">
                        <div class="panel panel-danger panel-pricing">
                        <div class="panel-heading">
                            <i class="fa fa-desktop"></i>
                            <h3>'.'<img src="/images/'. $campsiteData->getPhoto().'" alt="No Picture"/>'.'</h3>
                        </div>
                        <div class="panel-body text-center">
                            <p><strong> '.$campsiteData->getNameID(). '</strong></p>
                        </div>
                        <ul class="list-group text-center">
                            <li class="list-group-item"><i class="fa fa-check"></i> '.$campsiteData->getAddress().'</li>
                            <li class="list-group-item"><i class="fa fa-check"></i> '.$campsiteData->getOpeningDates().'</li>
                            <li class="list-group-item"><i class="fa fa-check"></i> '.$campsiteData->getVisitorRating().'</li>
                        </ul>
                        <div class="panel-footer">
                         <form action="/display.php" method="post">
                    <input type="hidden"  name="ID" value= "'.$campsiteDataSet->getID().'"/>
                            <button type="submit" class="btn btn-lg btn-block btn-danger" name="viewMore">View More</button>
                            </form>
                        </div>
                    </div>
                </div>
                </div>
                <!-- /item -->

    ';
        }

        ?>
    </table>
        </div>
    </div>
</section>


<!--</form>-->

<?php require('template/footer.phtml') ?>
