<?php require('template/header.phtml') ?>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <br/><br/><br/>

    <!-- Plans -->
    <section id="plans">
        <div class="container">
            <div class="row">

                <!-- item -->
                <div class="col-md-4 text-center">
                    <div class="panel panel-danger panel-pricing">
                        <div class="panel-heading">
                            <i class="fa fa-desktop"></i>
                            <img src="/images/france.jpg" height="300" width="240">
                        </div>
                        <div class="panel-body text-center">
                            <p><strong>Campsites in France</strong></p>
                        </div>


<!--                        <ul class="list-group text-center">-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> Personal use</li>-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> Unlimited projects</li>-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> 27/7 support</li>-->
<!--                        </ul>-->
                        <div class="panel-footer">
                            <a class="btn btn-lg btn-block btn-danger" href="campsiteISv1.php?location=france" name="france">VIEW MORE</a>
                        </div>
                    </div>
                </div>
                <!-- /item -->

                <!-- item -->
                <div class="col-md-4 text-center">
                    <div class="panel panel-danger panel-pricing">
                        <div class="panel-heading">
                            <i class="fa fa-desktop"></i>
                            <img src="/images/england.jpg" height="300" width="240">
                        </div>
                        <div class="panel-body text-center">
                            <p><strong>Campsites in England</strong></p>
                        </div>
<!--                        <ul class="list-group text-center">-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> Personal use</li>-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> Unlimited projects</li>-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> 27/7 support</li>-->
<!--                        </ul>-->
                        <div class="panel-footer">
                            <a class="btn btn-lg btn-block btn-danger" href="campsiteISv1.php?location=england" name="england">VIEW MORE</a>
                        </div>
                    </div>
                </div>
                <!-- /item -->

                <div class="col-md-4 text-center">
                    <div class="panel panel-danger panel-pricing">
                        <div class="panel-heading">
                            <i class="fa fa-desktop"></i>
                            <img src="/images/italy.jpg" height="300" width="240">
                        </div>
                        <div class="panel-body text-center">
                            <p><strong>Campsites in Italy</strong></p>
                        </div>
<!--                        <ul class="list-group text-center">-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> Personal use</li>-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> Unlimited projects</li>-->
<!--                            <li class="list-group-item"><i class="fa fa-check"></i> 27/7 support</li>-->
<!--                        </ul>-->
                        <div class="panel-footer">
                            <a class="btn btn-lg btn-block btn-danger" href="campsiteISv1.php?location=italy" name="italy">VIEW MORE</a>
                        </div>
                    </div>
                </div>
                <!-- /item -->

            </div>
        </div>
    </section>
    <!-- /Plans -->


<?php require('template/footer.phtml') ?>