<?php require('template/header.phtml') ?>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <h2>Login / Registration form</h2>
    </div>
</div>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="form-body">
                <ul class="nav nav-tabs final-login">
                    <li class="active"><a data-toggle="tab" href="#sectionA">Sign In</a></li>
                    <li><a data-toggle="tab" href="#sectionB">Sign up</a></li>
                </ul>

<!--                LOGIN START-->

                <div class="tab-content">
                    <div id="sectionA" class="tab-pane fade in active">
                        <div class="innter-form">
                            <form class="sa-innate-form" method="post"  action="/login2.php">
                                <label>Email Address</label>
                                <input type="text" name="email" required>
                                <label>Password</label>
                                <input type="password" name="pass" required>
                                <button type="submit" name="loginUser" >Sign In</button>
                            </form>
                        </div>
                        <div class="social-login">
                            <!--                LOGIN END-->



                            <!--                 REGISTER START-->

                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div id="sectionB" class="tab-pane fade">
                        <div class="innter-form">
                            <form class="sa-innate-form" method="post" action="/register.php">
                                <label>Name</label>
                                <input type="text" name="username" required>
                                <label>Email Address</label>
                                <input type="text" name="emailAddress" required>
                                <label>Password</label>
                                <input type="password" name="password" required>
                                <button type="submit" name="submit" >Join now</button>
                                <p>By clicking Join now, you agree to our User Agreement, Privacy Policy, and Cookie Policy.</p>
                            </form>
                        </div>
                        <!--                        REGISTER END    -->

                        <div class="social-login">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<?php require('template/footer.phtml') ?>
